DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS REPAIR;
DROP TABLE IF EXISTS ITEMTAG;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS WAITINGLIST;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS RESERVE;
DROP TABLE IF EXISTS REQUISITION;
DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS READER;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS REPAIRCOMPANY;
DROP TABLE IF EXISTS CITY;

CREATE TABLE CITY
(
IDCITY INTEGER NOT NULL PRIMARY KEY,
NAME TEXT NOT NULL
);

CREATE TABLE REPAIRCOMPANY
(
IDREPAIRCOMPANY INTEGER NOT NULL PRIMARY KEY,
COMPANYNAME TEXT NOT NULL,
IDCITY REFERENCES CITY(IDCITY) NOT NULL
);

CREATE TABLE ADMIN
(
IDADMIN INTEGER NOT NULL PRIMARY KEY,
PASSWORD UNIQUE NOT NULL,
USERNAME UNIQUE NOT NULL,
);

CREATE TYPE READERSTATUS AS ENUM ('BLOCK', 'ACTIVE', 'CLOSED');

CREATE TABLE READER
(
IDREADER INTEGER NOT NULL PRIMARY KEY,
PASSWORD UNIQUE NOT NULL,
USERNAME UNIQUE NOT NULL,
ADDRESS TEXT,
BIRTHDATE DATE,
EMAIL UNIQUE NOT NULL,
FIRSTNAME TEXT NOT NULL,
LASTNAME TEXT,
CURRENTSTATUS READERSTATUS NOT NULL
);

CREATE TABLE MANAGER
(
IDMANAGER INTEGER NOT NULL PRIMARY KEY,
IDINVENTORY REFERENCES INVENTORY(IDINVENTORY) NOT NULL
);

CREATE TYPE REQUISITIONSTATUS AS ENUM ('CLOSED', 'OPEN');

CREATE TABLE REQUISITION
(
IDREQUISTION INTEGER NOT NULL PRIMARY KEY,
COMMENT TEXT NOT NULL,
DELIVERYDATE DATE NOT NULL CHECK(DELIVERYDATE <= FINALDATE),
FINALDATE DATE NOT NULL,
INITIALDATE DATE NOT NULL CHECK(INITIALDATE <= FINALDATE),
NUMBEROFRENEWALS INTEGER NOT NULL CHECK(NUMBEROFRENEWALS >= 0),
CURRENTSTATUS REQUISITIONSTATUS NOT NULL
IDREADER REFERENCES READER(IDREADER) NOT NULL,
IDITEM REFERENCES ITEM(IDITEM) NOT NULL
);

CREATE TYPE RESERVESTATUS AS ENUM ('CLOSED', 'OPEN');

CREATE TABLE RESERVE
(
IDRESERVE INTEGER NOT NULL PRIMARY KEY,
EXPIREDATE DATE NOT NULL,
RESERVEDATE DATE NOT NULL CHECK(RESERVEDATE <= EXPIREDATE),
CURRENTSTATUS RESERVESTATUS NOT NULL,
IDREADER REFERENCES READER(IDREADER) NOT NULL,
IDITEM REFERENCES ITEM(IDITEM) NOT NULL
);

CREATE TYPE ITEMSTATUS AS ENUM ('AVAILABLE', 'REPAIR', 'WITHDRAWN', 'UNAVAILABLE');

CREATE TABLE ITEM
(
IDITEM INTEGER NOT NULL PRIMARY KEY,
DESCRIPTION TEXT NOT NULL,
IMAGE TEXT,
NAME TEXT NOT NULL,
QRCODE TEXT,
CURRENTSTATUS ITEMSTATUS NOT NULL,
IDINVENTORY REFERENCES INVENTORY(IDINVENTORY) NOT NULL
);

CREATE TABLE WAINTINGLIST
(
IDREADER REFERENCES READER(IDREADER) NOT NULL PRIMARY KEY,
IDITEM REFERENCES ITEM(IDITEM) NOT NULL PRIMARY KEY
);

CREATE TABLE TAG
(
IDTAG INTEGER NOT NULL PRIMARY KEY,
NAME TEXT NOT NULL
);

CREATE TABLE ITEMTAG
(
IDITEM REFERENCES ITEM(IDITEM) NOT NULL PRIMARY KEY,
IDTAG REFERENCES TAG(IDTAG) NOT NULL PRIMARY KEY
);

CREATE TABLE REPAIR
(
IDREPAIR INTEGER NOT NULL PRIMARY KEY,
FINALDATE DATE NOT NULL,
INITIALDATE DATE NOT NULL CHECK(INITIALDATE <= FINALDATE),
REASON TEXT NOT NULL,
IDREPAIRCOMPANY REFERENCES REPAIRCOMPANY(IDREPAIRCOMPANY) NOT NULL
);

CREATE TABLE INVENTORY
(
IDINVENTORY INTEGER NOT NULL PRIMARY KEY,
NAME TEXT NOT NULL
);

CREATE TYPE ALERTCATEGORY AS ENUM ('REQUESTRECEIPT', 'EXPIRE', 'ITEMAVAILABILITY', 'RECEPTIONRECEIPT');

CREATE TABLE ALERT
(
IDALERT INTEGER NOT NULL PRIMARY KEY,
CATERGORY ALERTCATEGORY NOT NULL
CONTENT TEXT NOT NULL,
CREATEDON DATE NOT NULL,
IDITEM REFERENCES ITEM(IDITEM) NOT NULL,
IDREADER REFERENCES READER(IDREADER) NOT NULL
IDMANAGER REFERENCES MANAGER(IDMANAGER) NOT NULL
);